all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: root

  children:
    perf_nodes:
      hosts:
        pgperf-01.prod.home.arpa:
          ansible_host: 10.10.92.121

  vars:
    ansible_user: "{{ lookup('env', 'CI_USER') | default('aurus', true) }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
